// Arama yapılacak kelimeler
const searchKeywords = {
    "tarih": "tarih",
    "şehir": "tarih",
    "izinde": "tarih",
    "rize": "tarih",
    "rize tarihi": "tarih",
    "video": "video",
    "rize videosu": "video",
    "tablo": "tablo",
    "nüfus": "tablo",
    "yıllık nüfus artış hızı": "tablo",
    "net göç": "tablo",
    "işsizlik oranı": "tablo",
    "yaş ortalaması": "tablo",
    "yüz ölçümü": "tablo",
    "şehirleşme oranı": "tablo",
    "nüfus yoğunluğu": "tablo",
    "koordinat": "tablo",
    "saat dilimi": "tablo",
    "komşu şehirler": "tablo",
    "büyük ilçeleri": "tablo",
    "merkez nüfus": "tablo",
    "iklim": "tablo",
    "telefon kodu": "tablo",
    "ihracat tutarı": "tablo",
    "ithalat tutarı": "tablo",
    "ticaret ve sanayi odası üyesi": "tablo",
    "enflasyon oranı": "tablo",
    "ana ihracat kaynakları": "tablo",
    "ana ithalat kaynakları": "tablo",
    "tarım ürünleri": "tablo",
    "yeraltı kaynakları": "tablo",
    "mamul mallar": "tablo",
    "ticaret anlaşmaları": "tablo",
    "havaalanı": "tablo",
    "sınır kapısı uzaklık": "tablo",
    "yolculuk": "gezi",
    "ayder": "gezi",
    "ayder yaylası": "gezi",
    "zil kalesi": "gezi",
    "zil": "gezi",
    "kayıkhane": "gezi",
    "rize kalesi": "gezi",
    "kale": "gezi",
    "ziraat çay bahçesi": "gezi",
    "ziraat çay": "gezi",
    "ziraat": "gezi",
    "elevit yaylası": "gezi",
    "elevit": "gezi",
    "çay çarşısı": "gezi",
    "çarşı": "gezi",
    "rize çay çarşısı": "gezi",
    "anzer yaylası": "gezi",
    "anzer": "gezi",
    "kız kalesi": "gezi",
    "kaçkar dağları": "gezi",
    "kaçkar": "gezi",
    "andon kaplıcaları": "gezi",
    "andon": "gezi",
    "atatürk evi müzesi": "gezi",
    "atatürk evi": "gezi",
    "müze": "gezi",
    "pokut yaylası": "gezi",
    "pokut": "gezi",
    "handüzü yaylası": "gezi",
    "handüzü": "gezi",
    "kordon sahil": "gezi",
    "sahil": "gezi",
    "kordon": "gezi",
    "palovit şelalesi": "gezi",
    "palovit": "gezi",
    "şelale": "gezi",
    "gito yaylası": "gezi",
    "gito": "gezi",
    "ovit yaylası": "gezi",
    "ovit": "gezi",
    "huser yaylası": "gezi",
    "huser": "gezi",
    "şeyh cami": "gezi",
    "şeyh": "gezi",
    "cami": "gezi",
    "bungalov evler": "gezi",
    "bungalov": "gezi",
    "fırtına deresi": "gezi",
    "fırtına": "gezi",
    "dere": "gezi",
    "pileki mağarası": "gezi",
    "pileki": "gezi",
    "mağara": "gezi",
    "ısırlık tabiat parkı": "gezi",
    "ısırlık tabiat": "gezi",
    "ısırlık": "gezi",
    "park": "gezi",
    "deniz feneri sosyal tesis": "gezi",
    "deniz feneri": "gezi",
    "fener": "gezi",
    "sosyal tesis": "gezi",
    "tesis": "gezi",
    "çeçeva köyü": "gezi",
    "çeçeva": "gezi",
    "köy": "gezi",
    "ağaran şelalesi": "gezi",
    "ağaran": "gezi",
    "kıbledağı cami": "gezi",
    "kıbledağı": "gezi",
    "şimşir ormanı": "gezi",
    "şimşir": "gezi",
    "çat vadisi": "gezi",
    "çat": "gezi",
    "vadi": "gezi",
    "gelintülü şelalesi": "gezi",
    "gelintülü": "gezi",
    "badara yaylası": "gezi",
    "badara": "gezi",
    "hazindak yaylası": "gezi",
    "hazindak": "gezi",
    "kavrun yaylası": "gezi",
    "kavrun": "gezi",
    "samistal yaylası": "gezi",
    "samistal": "gezi",
    "komati yaylası": "gezi",
    "komati": "gezi",
    "geleneksel lezzetler": "yemek",
    "yemek": "yemek",
    "muhlama": "yemek",
    "rize kavurması": "yemek",
    "hurda": "yemek",
    "kavurma": "yemek",
    "hamsili pilav": "yemek",
    "pilav": "yemek",
    "mısır ekmeği": "yemek",
    "ekmek": "yemek",
    "mısır": "yemek",
    "karalahana çorbası": "yemek",
    "karalahana": "yemek",
    "çorba": "yemek",
    "derepazarı pidesi": "yemek",
    "pide": "yemek",
    "derepazarı": "yemek",
    "hamsikoli": "yemek",
    "turşu tavalisi": "yemek",
    "turşu": "yemek",
    "tavali": "yemek",
    "çay maması": "yemek",
    "mama": "yemek",
    "doğrama": "yemek",
    "enişte lokumu": "yemek",
    "lokum": "yemek",
    "enişte": "yemek",
    "laz böreği": "yemek",
    "laz": "yemek",
    "börek": "yemek",
    "pepeçura": "yemek",
    "turbo sütlaç": "yemek",
    "turbo": "yemek",
    "sütlaç": "yemek",
    "kocakarı gerdanı": "yemek",
    "kocakarı": "yemek",
    "baklava": "yemek",
    "gerdan": "yemek",
    "pekmezli kabak reçeli": "yemek",
    "kabak reçeli": "yemek",
    "reçel": "yemek",
    "kabak sütlacı": "yemek",
    "kabak": "yemek",
    "sütlac": "yemek",
    "vurma lahana": "yemek",
    "lahana": "yemek",
    "karalahana haşlaması": "yemek",
    "haşlama": "yemek",
    "etli karalahana sarması": "yemek",
    "etli sarma": "yemek",
    "sarma": "yemek",
    "kabak pilavı": "yemek",
    "hurdalı çığırtma": "yemek",
    "çığırtma": "yemek",
    "hamsi tava": "yemek", 
    "hamsi": "yemek",
    "balık çorbası": "yemek",
    "balık": "yemek",
    "çorba": "yemek",
    "çayeli kurufasulye": "yemek",
    "kurufasulye": "yemek",
    "kuru fasulye": "yemek",
    "çayeli kuru fasulye": "yemek",
    "sanat": "sanat",
    "rize sanatı": "sanat",
    "el sanat": "sanat",
    "rize bezi": "sanat",
    "feretiko": "sanat",
    "bez": "sanat",
    "hemşin çorabı": "sanat",
    "çorap": "sanat",
    "hemşin": "sanat",
    "rize simidi": "sanat",
    "simit": "sanat",
    "rize sepeti": "sanat",
    "sepet": "sanat",
    "bakır": "sanat",
    "çay": "sanat",
    "rize hasır iskemle": "sanat",
    "hasır iskemle": "sanat",
    "hasır": "sanat",
    "iskemle": "sanat",
    "anzer balı": "sanat",
    "karadeniz kemençesi": "sanat",
    "kemençe": "sanat",
    "tulum": "sanat",
    "horon": "sanat",
    "keşan bezi": "sanat",
    "keşan": "sanat",
    "rize tipi puşi": "sanat",
    "puşi": "sanat",
    "enstrüman": "sanat",
};

document.querySelector('.search-bar button').addEventListener('click', function () {
    const query = document.querySelector('.search-bar input').value.toLowerCase();

    if (searchKeywords[query]) {
        document.getElementById(searchKeywords[query]).scrollIntoView({ behavior: 'smooth' });
    } else {
        alert("Aradığınız kelime bulunamadı.");
    }
});
